export const authors = [
  {
    id: 'authors-1',
    firstName: 'John',
    lastName: 'Smith',
    image: 'https://example.com/john_smith.jpg',
    bio: 'John Smith is a renowned author known for his compelling novels.',
    books: ['Book 1', 'Book 2'],
  },
  {
    id: 'authors-2',
    firstName: 'Jane',
    lastName: 'Doe',
    image: 'https://example.com/jane_doe.jpg',
    bio: 'Jane Doe is a bestselling author of mystery and suspense novels.',
    books: ['Mystery Book', 'Suspenseful Thriller'],
  },
  {
    id: 'authors-3',
    firstName: 'Michael',
    lastName: 'Johnson',
    image: 'https://example.com/michael_johnson.jpg',
    bio: 'Michael Johnson is a fantasy writer with a vivid imagination.',
    books: ['Fantasy World', 'Magical Realms'],
  },
  {
    id: 'authors-4',
    firstName: 'Emily',
    lastName: 'Brown',
    image: 'https://example.com/emily_brown.jpg',
    bio: 'Emily Brown is a poet who has touched the hearts of many with her words.',
    books: ['Poetry Collection', 'Verse of Emotions'],
  },
  {
    id: 'authors-5',
    firstName: 'David',
    lastName: 'Wilson',
    image: 'https://example.com/david_wilson.jpg',
    bio: 'David Wilson is a historian and author of several historical non-fiction books.',
    books: ['History of the World', 'Ancient Civilizations'],
  },
  {
    id: 'authors-6',
    firstName: 'Sarah',
    lastName: 'Lee',
    image: 'https://example.com/sarah_lee.jpg',
    bio: 'Sarah Lee writes young adult fiction and has a passion for storytelling.',
    books: ['Young Adult Adventures', 'Coming of Age'],
  },
  {
    id: 'authors-7',
    firstName: 'Robert',
    lastName: 'Turner',
    image: 'https://example.com/robert_turner.jpg',
    bio: 'Robert Turner is a sci-fi author known for his imaginative tales of the future.',
    books: ['Sci-Fi Odyssey', 'Space Explorers'],
  },
  {
    id: 'authors-8',
    firstName: 'Linda',
    lastName: 'Harris',
    image: 'https://example.com/linda_harris.jpg',
    bio: 'Linda Harris is a romance novelist who writes heartwarming love stories.',
    books: ['Romantic Escapes', 'Love in Bloom'],
  },
  {
    id: 'authors-9',
    firstName: 'James',
    lastName: 'Clark',
    image: 'https://example.com/james_clark.jpg',
    bio: 'James Clark is a renowned mystery writer with a knack for suspense.',
    books: ['Mystery Unveiled', 'Whodunit Chronicles'],
  },
  {
    id: 'authors-10',
    firstName: 'Anna',
    lastName: 'Martinez',
    image: 'https://example.com/anna_martinez.jpg',
    bio: 'Anna Martinez is a science writer who makes complex topics accessible to all.',
    books: ['Science Simplified', 'Discovering the Universe'],
  },
];
